.dockerignore, .github/workflows/ci.yml, Dockerfile.dev, Dockerfile.prod, README.md, docker-compose.yml
- added github action yml file
- added Dockerfile for development and production environments
- added docker-compose file (makes workflow easier)
- added setup documentation in README.md file
- NOTE: I need to test if github actions works when a PR is made to the develop
=> feat: added docker workflow with github actions and docker-compose. I also added some documentation to the README.md with instructions for setup

package.json, pnpm-lock.yaml
Reverts LetsGetTechnical/gridiron-survivor#128
=> Revert "PR: 127-install-sass-for-the-main-app"

app/register/page.tsx
- fix issue where registration redirect to weekly picks when no user is logged in
=> small change to register page

app/login/layout.tsx, app/login/page.tsx
Closes #168 
Created new layout just for the login page that omits the navbar.
=> Create new Layout for login page

app/login/page.tsx, app/register/page.tsx
1) added underline to links for `register` and `login` page.tsx files
=> added underline classname to hyperlinks

app/login/page.tsx
- fix bug in login that immediately redirects users to weeklypicks page
=> Login page bug

app/layout.tsx
`export const metadata = {
metadataBase: new URL(defaultUrl),
title: 'GridIron Survivor',
description: 'Fantasy Football Survivor Pool',
};
`
=> update title tag to GridIron Survivor

app/layout.tsx, package.json, pnpm-lock.yaml
fixes #292 
implemented [React Hot Toast](https://react-hot-toast.com/) to utilize alerts throughout the application.
React Hot Toast is fully customizeable for the UX team 🚀
**NOTE:** This required installing a new pnpm package so be sure to run `pnpm install` to get the lastest package.
=> feat(#292): add alert functionality to access across application

app/league/[leagueId]/entries/[entryId]/week/Week.interface.ts, app/league/[leagueId]/entries/[entryId]/week/Week.tsx, app/league/[leagueId]/entries/[entryId]/week/WeekTeams.interface.ts, app/league/[leagueId]/entries/[entryId]/week/WeekTeams.tsx, app/league/[leagueId]/entries/[entryId]/week/[weekId]/page.tsx, next.config.js
=> feat #307: adding dynamic NFL schedule for the week page

components/Alert/Alert.tsx, components/LeagueCard/LeagueCard.tsx
=> #429 FIX: forwardRef errors in console

.eslintignore, .eslintrc.json, functions/userAuth.js, jest.setup.js, middleware.ts, next.config.js, package.json, playwright.config.ts, postcss.config.js, prettier.config.js, tsconfig.json
fixes #439 
- Errors now showing on build and will now exit the build process on any eslint error
- All file changes had to do with config and/or fixing errors now that they are showing up.
=> #439 FIX: eslint error rules being ignored on build

components/AdminHeader/AdminHeader.tsx, components/AdminLogo/AdminLogo.tsx, components/AdminNav/AdminNav.test.tsx, components/AdminNav/AdminNav.tsx, components/AdminQuickMenu/AdminQuickMenu.test.tsx, components/AdminUserSettings/AdminUserSettings.tsx
Closes #466 
Fixed typo in `AdminNav` and sorted imports in various Admin components. Also refined `AdminQuickMenu` test to make variable consistent with component being tested.
=> chore: cleanup adminLayout commit

app/(main)/league/[leagueId]/entry/all/page.test.tsx, app/(main)/league/[leagueId]/entry/all/page.tsx
fixes #496 
✅ Limits user to 5 entries
✅ Updated Unit Test
=> #496 Chris/Limit-User-Entries

.eslintignore, api/apiFunctions.enum.ts, api/apiFunctions.interface.ts, api/apiFunctions.test.tsx, api/apiFunctions.ts, app/(main)/league/[leagueId]/entry/Entries.interface.ts, app/(main)/league/[leagueId]/entry/[entryId]/week/Week.interface.ts, app/(main)/league/[leagueId]/entry/[entryId]/week/Week.test.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/Week.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/WeekHelper.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/WeekTeams.interface.ts, app/(main)/league/[leagueId]/entry/[entryId]/week/WeekTeams.test.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/WeekTeams.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/__mocks__/mockSchedule.ts, app/(main)/league/[leagueId]/entry/all/page.test.tsx, app/(main)/league/[leagueId]/entry/all/page.tsx, app/(main)/league/all/page.test.tsx, app/(main)/league/all/page.tsx, app/(main)/register/page.test.tsx, app/(main)/register/page.tsx, components/GlobalSpinner/GlobalSpinner.test.tsx, components/Label/Label.tsx, components/WeeklyPickButton/WeeklyPickButton.tsx, context/AuthContextProvider.tsx, package.json, store/dataStore.test.ts, store/dataStore.ts, utils/utils.test.ts, utils/utils.ts
=> Release v0.4.0-alpha

package.json
- force dark mode for all users
- update game collection results per week per league
=> Release v0.3.1-alpha

app/(main)/league/[leagueId]/entry/[entryId]/week/Week.test.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/Week.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/WeekHelper.tsx, app/(main)/league/[leagueId]/entry/all/page.test.tsx, app/(main)/league/[leagueId]/entry/all/page.tsx, components/LeagueEntries/LeagueEntries.interface.ts, components/LeagueEntries/LeagueEntries.test.tsx, components/LeagueEntries/LeagueEntries.tsx, utils/utils.ts
=> #529 Chris/Show Users Previous Picks

app/(main)/layout.tsx
Closes #545 
As per @shashilo:
> Oh P0! We need a floating something so folks can click it to go to the Google form and provide feedback.
https://github.com/user-attachments/assets/c8e7b538-936b-4364-b9b0-ee2a21c488e1
=> create and add feedback CTA

app/(main)/account/recovery/page.tsx, app/(main)/login/page.tsx, app/(main)/register/page.test.tsx, app/(main)/register/page.tsx
Change the UI to say 8 characters for the password instead of 6.
=> Alex/Change UI for Password Input

package.json
update package.json to 0.4.0 for alpha release.
=> build: update app version to 0.4.0-alpha

app/(main)/league/[leagueId]/entry/[entryId]/week/Week.test.tsx, app/(main)/league/[leagueId]/entry/[entryId]/week/Week.tsx
Reverts LetsGetTechnical/gridiron-survivor#557
=> Revert "Temporary locked picking a team"
